apiVersion: v1
kind: Pod
metadata:
  name: "throughput"
  namespace: "default"
  labels:
    app: throughput
spec:
  containers:
    - name: "throughput"
      args: [
        "-sessions=50",
        "-tls_ca_file=/etc/robustirc/tls/cert.pem",
        "-listen=:9979",
        "-network=robustirc-node-1:8443,robustirc-node-2:8443,robustirc-node-3:8443",
        "-network_config_file=/etc/robustirc/config/config.toml",
        "-prometheus=prometheus:9090",
        "-snapshot_dashboards=/etc/robustirc/dashboards/robustirc.json,/etc/robustirc/dashboards/robustirc-loadtest.json",
      ]
      env:
      - name: ROBUSTIRC_NETWORK_PASSWORD
        value: "k8s"
      image: "eu.gcr.io/robustirc-loadtest/benchmark"
      imagePullPolicy: Always
      ports:
      - name: throughput
        containerPort: 9979
      volumeMounts:
      - name: tls
        mountPath: /etc/robustirc/tls
        readOnly: true
      - name: config
        mountPath: /etc/robustirc/config
        readOnly: true
      - name: dashboards
        mountPath: /etc/robustirc/dashboards
        readOnly: true
  restartPolicy: Never
  volumes:
  - name: tls
    configMap:
      name: tls
  - name: config
    configMap:
      name: config
  - name: dashboards
    configMap:
      name: dashboards
